## App Deployment manifest ## 
## Type : Deployment 
## Image from registry 
## name : app1
## labels :  app = app1 , env = dev
## Replicas = 3
## Namespace = default

apiVersion: v1
kind: Namespace
metadata:
  name: app1-ns
  labels:
    app: app1
    env: dev
    type: flask

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app1-ns
  name: app1
  labels:
    app: app1
    env: dev
    type: flask
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app1
      env: dev
  template:
    metadata:
      name: app1-pod
      labels:
        app: app1
        env: dev
    spec: 
      containers:
      - name: app1-container
        image: httpd:latest  #burkanoves/k8s-app:0.3.1   #zsalieva/python-app:latest 
        ports:
        - containerPort: 5000