apiVersion: v1
kind: Service
metadata:
 # namespace: app1-ns
  name: app-lb-service
spec:  
  type: LoadBalancer
  selector:
      app: app1
      env: dev
      type: flask
  ports:
    - name: httpd
      protocol: TCP
      port: 80
      targetPort: 5000

  
