apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: app1-pvc
  labels: 
    app: app1
    env: dev
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi