apiVersion: v1 
kind: PersistentVolume
metadata:
  name: app1-container-pvc
  labels: 
    app: app1
    env: dev
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/app1-container"