apiVersion: v1
kind: Pod
metadata:
  name: nginx-vol
spec:
  containers:
  - name: nginx-1 #container1
    image: nginx:latest
    volumeMounts:
      - name: nginx-volume #volume
        mountPath: /app/data #inside the container path
  - name: nginx-2 #container2
    image: nginx:latest
    volumeMounts:
      - name: nginx-volume #volume
        mountPath: /app/data #inside the container path       
  volumes: 
  - name: nginx-volume1

    emptyDir: {}