apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  labels: 
    app: nginx
    env: dev
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi