apiVersion: v1
kind: Service
metadata:
  name: httpd-server
  labels:
    run: pod-httpd
spec:
    type: NodePort
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
      nodePort: 30050
    selector:
     run: pod  
  
