apiVersion: v1
kind: PersistentVolume
metadata:
  name: flask-persistent-volume
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/flask-app"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-app-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: flask
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask
      env: dev
  template:
    metadata:
      labels:
        app: flask
        env: dev
    spec:
      volumes:
        - name: flask-pv-storage
          persistentVolumeClaim:
            claimName: flask-app-claim
      containers:
        - name: flask-app
          image: burkanoves/k8s-app:0.3.1
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: "/data"
              name: flask-pv-storage

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-lb-service
spec:
  type: LoadBalancer
  selector:
    app: flask
    env: dev
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000